### ISSUE TITLE
[BUG] editing controls not aligned

### ISSUE THREAD

**Issue by robinsone** [arieh/TellMeWhen_Script_Tools#3]
From what I can see with the newest version of tellmewhen 10.0.7 the controls for scripted conditions are not aligned. 

![image](https://user-images.githubusercontent.com/1637696/212361566-8f626d3b-8520-489e-aeab-8b842fa66b4b.png)

As you can see in the screenshot above, the text field to enter you buff and the count slider overlap. This prevents you from being able to enter your buff/debuff in this case. This happens for each script tool condition that has these two inputs.

**Comment by arieh** [comment]
Hey!

I was not able to reproduce - can you try and reset the icon and re-create it? there might be some taint in the config that might cause this

**Comment by robinsone** [comment]
ok maybe I'll backup my strings and do a clean install.
