### ISSUE TITLE
Unit counter problem

### ISSUE THREAD

**Issue by ngmafia** [arieh/TellMeWhen_Script_Tools#6]
With a last update that Blizzard made left IsItemInRange a protected function.

The unit counter no longer works correctly and creates error messages.

**Comment by arieh** [comment]
Known issue. The new Range Checker is not as useful as the old one. I'm working on a fix.

**Comment by ngmafia** [comment]
I tried the update and it works but it checks the units at maximum range and not in melee like before.

**Comment by arieh** [comment]
This seems to be class/spec based. Basically if your spec doesnt have a melee-ranged spell then the LibRange library can't help.
My guess it will take time until a full fix will happen. The LibRange library used by this addon is supplied by both WA and TMW, so I suspect over time things will get better.
